name: Hello World

on: push

jobs:
    hello_world_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Echo text
              run: 'echo "Hello, World!"'